### ISSUE TITLE
train failed

### ISSUE THREAD

**Issue by fangg2024** [Text-to-Audio/Make-An-Audio#13]
The training failed and there were some problems. I strongly recommend that you download and operate from the beginning. I failed when I executed vae.xml. The code or parameters have been changed no less than 3 times. I found that the configuration file also had 'useful_ckpts/bigvnat' which is only available in Make-An-Audio-3. I can't change it here.

训练失败，强烈建议作者从头下载操作一次，我执行到vae时失败，代码或参数已经改了不下3次，我发现配置文件中还出现了Make-An-Audio-3才有的'useful_ckpts/bigvnat'，到这里我改不动了

`Summoning checkpoint.

Traceback (most recent call last):
  File "/home/test/other/tts/Make-An-Audio/main.py", line 780, in <module>
    trainer.fit(model, data)
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 700, in fit
    self._call_and_handle_interrupt(
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 652, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in _run_train
    self.fit_loop.run()
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 195, in run
    self.on_run_start(*args, **kwargs)
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 210, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1811, in reset_train_dataloader
    self.train_dataloader = self._data_connector._request_dataloader(RunningStage.TRAINING)
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 430, in _request_dataloader
    dataloader = source.dataloader()
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 507, in dataloader
    return method()
  File "/home/test/other/tts/Make-An-Audio/./main.py", line 217, in _train_dataloader
    return DataLoader(self.datasets["train"], batch_size=self.batch_size ,# sampler=DistributedSampler # np.arange(100),
  File "/home/test/.local/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py", line 491, in wrapper
    init(obj, *args, **kwargs)
  File "/home/test/.conda/envs/maa/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/test/.conda/envs/maa/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0
`

thanks

**Comment by fangg2024** [comment]
In addition, I tested 10 samples for training.
